# Generated by Django 6.0.7 on 2026-07-24 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourseSyllabus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="课程代码"
                    ),
                ),
                (
                    "course_name",
                    models.CharField(max_length=200, verbose_name="课程名称"),
                ),
                (
                    "course_name_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="英文名称"
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="学分"
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[("spring", "春季学期"), ("autumn", "秋季学期")],
                        max_length=10,
                        verbose_name="开课学期",
                    ),
                ),
                ("grade", models.CharField(max_length=20, verbose_name="适用年级")),
                ("major", models.CharField(max_length=100, verbose_name="适用专业")),
                (
                    "teacher_name",
                    models.CharField(max_length=100, verbose_name="授课教师"),
                ),
                ("course_objectives", models.TextField(verbose_name="课程目标")),
                ("course_content", models.TextField(verbose_name="课程内容")),
                (
                    "teaching_methods",
                    models.TextField(blank=True, verbose_name="教学方法"),
                ),
                (
                    "assessment_methods",
                    models.TextField(blank=True, verbose_name="考核方式"),
                ),
                (
                    "reference_materials",
                    models.TextField(blank=True, verbose_name="参考资料"),
                ),
                (
                    "prerequisite_courses",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="先修课程"
                    ),
                ),
                (
                    "file_upload",
                    models.FileField(
                        blank=True, upload_to="syllabus/", verbose_name="大纲文件"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "课程大纲",
                "verbose_name_plural": "课程大纲",
            },
        ),
        migrations.CreateModel(
            name="ExcellentWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="作品名称")),
                ("description", models.TextField(verbose_name="作品描述")),
                (
                    "work_type",
                    models.CharField(
                        choices=[
                            ("thesis", "毕业论文"),
                            ("design", "设计作品"),
                            ("competition", "竞赛作品"),
                            ("research", "科研成果"),
                            ("innovation", "创新项目"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="作品类型",
                    ),
                ),
                (
                    "author_name",
                    models.CharField(max_length=100, verbose_name="作者姓名"),
                ),
                (
                    "author_major",
                    models.CharField(max_length=100, verbose_name="作者专业"),
                ),
                (
                    "author_graduation_year",
                    models.CharField(max_length=4, verbose_name="毕业年份"),
                ),
                (
                    "supervisor",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="指导教师"
                    ),
                ),
                (
                    "awards",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="获奖情况"
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        upload_to="excellent_works/",
                        verbose_name="封面图片",
                    ),
                ),
                (
                    "file_upload",
                    models.FileField(
                        blank=True,
                        upload_to="excellent_works/",
                        verbose_name="作品文件",
                    ),
                ),
                ("link", models.URLField(blank=True, verbose_name="外部链接")),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="精选展示"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "优秀作品",
                "verbose_name_plural": "优秀作品",
            },
        ),
        migrations.CreateModel(
            name="SeniorMentor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, upload_to="senior_avatars/", verbose_name="头像"
                    ),
                ),
                ("major", models.CharField(max_length=100, verbose_name="专业")),
                (
                    "graduation_year",
                    models.CharField(
                        choices=[
                            ("2010", "2010"),
                            ("2011", "2011"),
                            ("2012", "2012"),
                            ("2013", "2013"),
                            ("2014", "2014"),
                            ("2015", "2015"),
                            ("2016", "2016"),
                            ("2017", "2017"),
                            ("2018", "2018"),
                            ("2019", "2019"),
                            ("2020", "2020"),
                            ("2021", "2021"),
                            ("2022", "2022"),
                            ("2023", "2023"),
                            ("2024", "2024"),
                            ("2025", "2025"),
                            ("2026", "2026"),
                            ("2027", "2027"),
                            ("2028", "2028"),
                            ("2029", "2029"),
                        ],
                        max_length=4,
                        verbose_name="毕业年份",
                    ),
                ),
                (
                    "current_status",
                    models.CharField(max_length=200, verbose_name="当前状态"),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="就职单位"
                    ),
                ),
                (
                    "position",
                    models.CharField(blank=True, max_length=100, verbose_name="职位"),
                ),
                ("education_background", models.TextField(verbose_name="教育背景")),
                ("experience_summary", models.TextField(verbose_name="经验总结")),
                (
                    "skills",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="技能标签"
                    ),
                ),
                ("achievements", models.TextField(blank=True, verbose_name="主要成就")),
                (
                    "advice",
                    models.TextField(blank=True, verbose_name="给学弟学妹的建议"),
                ),
                (
                    "contact_available",
                    models.BooleanField(default=True, verbose_name="可联系"),
                ),
                (
                    "mentor_type",
                    models.CharField(
                        choices=[
                            ("academic", "学术导师"),
                            ("career", "职业导师"),
                            ("competition", "竞赛导师"),
                            ("life", "生活导师"),
                        ],
                        default="career",
                        max_length=20,
                        verbose_name="导师类型",
                    ),
                ),
                (
                    "tags",
                    models.CharField(blank=True, max_length=500, verbose_name="标签"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "学长导师",
                "verbose_name_plural": "学长导师",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(max_length=50, unique=True, verbose_name="用户ID"),
                ),
                ("username", models.CharField(max_length=100, verbose_name="用户名")),
                (
                    "grade",
                    models.CharField(blank=True, max_length=20, verbose_name="年级"),
                ),
                (
                    "major",
                    models.CharField(blank=True, max_length=100, verbose_name="专业"),
                ),
                (
                    "gpa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="GPA",
                    ),
                ),
                (
                    "rank",
                    models.CharField(blank=True, max_length=50, verbose_name="排名"),
                ),
                ("awards", models.TextField(blank=True, verbose_name="获奖记录")),
                ("research", models.TextField(blank=True, verbose_name="科研经历")),
                ("goal", models.TextField(blank=True, verbose_name="未来目标")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "用户档案",
                "verbose_name_plural": "用户档案",
            },
        ),
        migrations.CreateModel(
            name="CourseRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("prerequisite", "先修"),
                            ("corequisite", "同修"),
                            ("advanced", "进阶"),
                            ("related", "关联"),
                            ("complementary", "互补"),
                        ],
                        max_length=20,
                        verbose_name="关联类型",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="关联描述")),
                (
                    "strength",
                    models.IntegerField(default=50, verbose_name="关联强度(1-100)"),
                ),
                ("verified", models.BooleanField(default=False, verbose_name="已验证")),
                (
                    "source_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relations",
                        to="chat.coursesyllabus",
                        verbose_name="源课程",
                    ),
                ),
                (
                    "target_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relations",
                        to="chat.coursesyllabus",
                        verbose_name="目标课程",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程关联",
                "verbose_name_plural": "课程关联",
            },
        ),
        migrations.CreateModel(
            name="AnonymousFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("course", "课程反馈"),
                            ("teacher", "教师评价"),
                            ("facility", "设施建议"),
                            ("management", "管理建议"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="反馈类型",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("content", models.TextField(verbose_name="反馈内容")),
                (
                    "is_anonymous",
                    models.BooleanField(default=True, verbose_name="匿名"),
                ),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="已解决"),
                ),
                (
                    "resolution_content",
                    models.TextField(blank=True, verbose_name="处理结果"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="处理时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "related_course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chat.coursesyllabus",
                        verbose_name="关联课程",
                    ),
                ),
            ],
            options={
                "verbose_name": "匿名反馈",
                "verbose_name_plural": "匿名反馈",
            },
        ),
        migrations.CreateModel(
            name="SeniorEmployment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("fulltime", "全职工作"),
                            ("graduate", "升学"),
                            ("study_abroad", "出国留学"),
                            ("startup", "创业"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="就业类型",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=200, verbose_name="单位名称"),
                ),
                (
                    "company_logo",
                    models.ImageField(
                        blank=True, upload_to="company_logos/", verbose_name="单位Logo"
                    ),
                ),
                ("industry", models.CharField(max_length=100, verbose_name="所属行业")),
                ("position", models.CharField(max_length=100, verbose_name="职位")),
                (
                    "department",
                    models.CharField(blank=True, max_length=100, verbose_name="部门"),
                ),
                (
                    "salary_range",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="薪资范围"
                    ),
                ),
                ("location", models.CharField(max_length=100, verbose_name="工作地点")),
                ("work_summary", models.TextField(blank=True, verbose_name="工作心得")),
                (
                    "recruitment_tips",
                    models.TextField(blank=True, verbose_name="求职建议"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="精选展示"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "senior",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employment",
                        to="chat.seniormentor",
                        verbose_name="学长",
                    ),
                ),
            ],
            options={
                "verbose_name": "学长就业",
                "verbose_name_plural": "学长就业",
            },
        ),
        migrations.CreateModel(
            name="SyllabusDuplicate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "similarity_score",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="相似度"
                    ),
                ),
                (
                    "duplicate_content",
                    models.TextField(blank=True, verbose_name="重复内容摘要"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("confirmed", "已确认"),
                            ("resolved", "已解决"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "checked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="检测时间"
                    ),
                ),
                (
                    "syllabus1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_source",
                        to="chat.coursesyllabus",
                        verbose_name="课程1",
                    ),
                ),
                (
                    "syllabus2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_target",
                        to="chat.coursesyllabus",
                        verbose_name="课程2",
                    ),
                ),
            ],
            options={
                "verbose_name": "大纲查重结果",
                "verbose_name_plural": "大纲查重结果",
            },
        ),
    ]
