# Generated by Django 6.0.7 on 2026-07-24 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="department",
            field=models.CharField(blank=True, max_length=100, verbose_name="所属院系"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="position",
            field=models.CharField(blank=True, max_length=100, verbose_name="职位"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[("student", "学生"), ("teacher", "教师"), ("admin", "管理员")],
                default="student",
                max_length=20,
                verbose_name="角色",
            ),
        ),
        migrations.CreateModel(
            name="CourseAnalysisReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ai_extracted_objectives",
                    models.JSONField(
                        blank=True, null=True, verbose_name="AI提取的课程目标"
                    ),
                ),
                (
                    "ai_extracted_points",
                    models.JSONField(
                        blank=True, null=True, verbose_name="AI提取的知识点"
                    ),
                ),
                (
                    "optimization_suggestions",
                    models.TextField(blank=True, verbose_name="优化建议"),
                ),
                (
                    "coverage_analysis",
                    models.JSONField(
                        blank=True, null=True, verbose_name="知识点覆盖分析"
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="生成时间"),
                ),
                (
                    "course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_report",
                        to="chat.coursesyllabus",
                        verbose_name="课程",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程分析报告",
                "verbose_name_plural": "课程分析报告",
            },
        ),
        migrations.CreateModel(
            name="FeedbackAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sentiment_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="情感得分(-1到1)",
                    ),
                ),
                (
                    "sentiment_label",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="情感标签"
                    ),
                ),
                (
                    "topics",
                    models.JSONField(blank=True, null=True, verbose_name="主题分类"),
                ),
                (
                    "keywords",
                    models.JSONField(blank=True, null=True, verbose_name="关键词"),
                ),
                ("summary", models.TextField(blank=True, verbose_name="反馈摘要")),
                (
                    "analyzed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="分析时间"),
                ),
                (
                    "feedback",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="chat.anonymousfeedback",
                        verbose_name="反馈",
                    ),
                ),
            ],
            options={
                "verbose_name": "反馈分析",
                "verbose_name_plural": "反馈分析",
            },
        ),
        migrations.CreateModel(
            name="GrowthPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path_type",
                    models.CharField(
                        choices=[
                            ("graduate_exam", "考研"),
                            ("graduate_recommend", "保研"),
                            ("employment", "就业"),
                            ("research", "科研"),
                            ("competition", "竞赛"),
                            ("study_abroad", "出国留学"),
                        ],
                        max_length=20,
                        verbose_name="路径类型",
                    ),
                ),
                (
                    "path_name",
                    models.CharField(max_length=200, verbose_name="路径名称"),
                ),
                (
                    "stages",
                    models.JSONField(blank=True, null=True, verbose_name="阶段规划"),
                ),
                (
                    "recommended_courses",
                    models.JSONField(blank=True, null=True, verbose_name="推荐课程"),
                ),
                (
                    "resources",
                    models.JSONField(blank=True, null=True, verbose_name="推荐资源"),
                ),
                (
                    "estimated_duration",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="预计时长"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="growth_paths",
                        to="chat.userprofile",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "成长路径",
                "verbose_name_plural": "成长路径",
            },
        ),
        migrations.CreateModel(
            name="KnowledgePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "point_name",
                    models.CharField(max_length=200, verbose_name="知识点名称"),
                ),
                (
                    "point_category",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="知识点类别"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="知识点描述"),
                ),
                (
                    "importance",
                    models.IntegerField(default=50, verbose_name="重要程度(1-100)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_points",
                        to="chat.coursesyllabus",
                        verbose_name="所属课程",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识点",
                "verbose_name_plural": "知识点",
            },
        ),
    ]
