# Generated by Django 6.0.7 on 2026-07-25 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_userprofile_department_userprofile_position_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="anonymousfeedback",
            name="target_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feedbacks",
                to="chat.userprofile",
                verbose_name="目标教师",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_completed",
            field=models.BooleanField(default=False, verbose_name="信息已完善"),
        ),
        migrations.CreateModel(
            name="StudentCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[("spring", "春季学期"), ("autumn", "秋季学期")],
                        max_length=10,
                        verbose_name="学期",
                    ),
                ),
                ("academic_year", models.CharField(max_length=10, verbose_name="学年")),
                (
                    "grade",
                    models.CharField(blank=True, max_length=20, verbose_name="成绩"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="选课时间"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="chat.coursesyllabus",
                        verbose_name="课程",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrolled_courses",
                        to="chat.userprofile",
                        verbose_name="学生",
                    ),
                ),
            ],
            options={
                "verbose_name": "学生选课",
                "verbose_name_plural": "学生选课",
                "unique_together": {("student", "course", "semester", "academic_year")},
            },
        ),
        migrations.CreateModel(
            name="TeacherCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[("spring", "春季学期"), ("autumn", "秋季学期")],
                        max_length=10,
                        verbose_name="学期",
                    ),
                ),
                ("academic_year", models.CharField(max_length=10, verbose_name="学年")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teachers",
                        to="chat.coursesyllabus",
                        verbose_name="课程",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teaching_courses",
                        to="chat.userprofile",
                        verbose_name="教师",
                    ),
                ),
            ],
            options={
                "verbose_name": "教师授课",
                "verbose_name_plural": "教师授课",
                "unique_together": {("teacher", "course", "semester", "academic_year")},
            },
        ),
    ]
