# Generated by Django 6.0.7 on 2026-07-25 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_anonymousfeedback_target_teacher_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="anonymousfeedback",
            name="is_public",
            field=models.BooleanField(default=False, verbose_name="公开反馈"),
        ),
        migrations.AddField(
            model_name="coursesyllabus",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_courses",
                to="chat.userprofile",
                verbose_name="创建教师",
            ),
        ),
    ]
