# Generated by Django 6.0.7 on 2026-07-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_anonymousfeedback_is_public_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email",
            field=models.CharField(blank=True, max_length=100, verbose_name="邮箱"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="联系电话"),
        ),
    ]
