# Generated by Django 6.0.7 on 2026-07-26 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_userprofile_email_userprofile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="excellentwork",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_works",
                to="chat.userprofile",
                verbose_name="创建教师",
            ),
        ),
    ]
