# Generated by Django 6.0.7 on 2026-07-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_excellentwork_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="anonymousfeedback",
            name="rating",
            field=models.IntegerField(default=5, verbose_name="评分(1-5星)"),
        ),
        migrations.AddField(
            model_name="anonymousfeedback",
            name="severity",
            field=models.CharField(
                choices=[("low", "低"), ("medium", "中"), ("high", "高")],
                default="medium",
                max_length=10,
                verbose_name="严重程度",
            ),
        ),
        migrations.AddField(
            model_name="anonymousfeedback",
            name="tags",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="标签(逗号分隔)"
            ),
        ),
    ]
