# Generated by Django 6.0.7 on 2026-07-27 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_anonymousfeedback_rating_anonymousfeedback_severity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="hometown",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="家乡地（省份/城市）"
            ),
        ),
    ]
