# Generated by Django 6.0.7 on 2026-07-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_userprofile_hometown"),
    ]

    operations = [
        migrations.AddField(
            model_name="anonymousfeedback",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="feedback_images/", verbose_name="反馈图片"
            ),
        ),
    ]
