# Generated by Django 6.0.7 on 2026-07-28 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_anonymousfeedback_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="anonymousfeedback",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_feedbacks",
                to="chat.userprofile",
                verbose_name="提交者",
            ),
        ),
    ]
